---
title: "Homework 2"
author: Vanessa Dinh
date: 10/8/22
output: github_document
---

```{r}
library(tidyverse)
```

## Probem 1

```{r}
nyc_subway = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude, starts_with("route"), 
         entry, entrance_type, vending, ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE),
         dist_station = paste(line, station_name),
         ada = ifelse(entry == "TRUE", TRUE, FALSE)) %>% 
  distinct(dist_station) 

# The nyc_subway dataset has the intersections of NYC subway stations, along with their latitude and longitude coordinates. It also reports what route the train is on, what kind of entrance is used to get to the subway station and if it is ADA compliant. To clean this dataset, I used the clean_names function in the janitor package, which turns all variable names into lowercase and separated by underscores. I also used select() to choose which variables to keep in the dataframe. I then used the mutate() function with ifelse() to make the entry variable a logical vector. These data are tidy.

#There are 465 distinct stations. 

```

## Problem 2

```{r}
mr_trash_wheel =
  readxl::read_excel(
    "./data/Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N549") %>%
  janitor::clean_names() %>% 
  mutate(sports_balls = as.integer(sports_balls),
          year = as.integer(year), 
          wheel_name = "mr_trash_wheel")

prof_trash_wheel =
  readxl::read_excel(
    "./data/Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M96") %>%
  janitor::clean_names() %>% 
  mutate(year = as.integer(year),
         wheel_name = "prof_trash_wheel")

mr_prof_trash_combined =
  bind_rows(mr_trash_wheel, prof_trash_wheel)

sum(prof_trash_wheel$weight_tons)
with(mr_trash_wheel, sum(sports_balls[year == 2020]))

# The combined dataset with both Mr. Trash Wheel and Professor Trash Wheel data has 641 observations.
# Some key variables include trash wheel name, dumpster number, date, weight in tons, and volume of trash in cubic yards.
# For available data, the total weight of trash collected by Professor Trash Wheel is 190.12 tons.
# Mr. Trash Wheel collected 856 sports balls in 2020.

```

## Problem 3

```{r}
polit_party =
  read_csv("./data/pols-month.csv")%>% 
  janitor::clean_names() %>% 
  separate(
    mon,
    into = c("year", "month", "day"),
    sep = '-') %>% 
  mutate(year = as.integer(year),
         month = as.integer(month),
         day = as.integer(day),
         month = month.name[month]) %>% 
  relocate(prez_gop, prez_dem) %>% 
  pivot_longer(
    prez_gop:prez_dem,
    names_to = "president",
    values_to = "president_num",
    names_prefix = "prez_") %>% 
  filter(president_num != 0) %>% 
  select(-president_num, -day)

```

```{r}
snp_stocks = 
  read_csv("./data/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(
    date,
    into = c("month", "day", "year"),
    sep = '/') %>% 
  mutate(year = as.integer(year),
         month = as.integer(month),
         day = as.integer(day),
         month = month.name[month],
         year = ifelse(year < 20, year + 2000, year + 1900),
         year = as.integer(year)) %>% 
  relocate(year, month) %>% 
  select(-day)

```

```{r}
unemployment = 
  read_csv("./data/unemployment.csv") %>% 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "perc_unemployed") %>% 
  mutate(month = factor(month, levels = month.abb, labels = month.name),
         month = as.character(month),
         year = as.integer(Year)) %>% 
  relocate(year, month) %>% 
  select(-Year) 

```

```{r}
snp_polit = 
  left_join(polit_party, snp_stocks)

unemploy_snp_polit =
  left_join(snp_polit, unemployment)

nrow(polit_party)
ncol(polit_party)
nrow(snp_stocks)
ncol(snp_stocks)
nrow(unemployment)
ncol(unemployment)
nrow(snp_polit)
ncol(snp_polit)
nrow(unemploy_snp_polit)
ncol(unemploy_snp_polit)

# The pols-month and polit_party datasets have 822 observations and 9 variables with a range of years from 1947 to 2015. Some of its key variables are the date of the count, and the number of national politicians who are Democratic or Republican (e.g. gov_gop, gov_dem).

#The snp initial dataset had 2 variables for date and close, the closing values of the S&P stock index, and 787 observations ranging from year 1950 to 2015. The resulting snp_stocks dataset has 787 observations and 3 variables, with the date split up by month and year. 

# The initial unemployment dataset had 69 "observations"/rows and 13 variables, one column for year and the others for month, with the unemployment percentage as the values in the dataset. However, the resulting unemployment dataset after data manipulation has 816 observations and 3 variables where the months were condensed into a single column and the percent unemployed pivoted longer. 

#The snp_polit merged dataset has 822 observations and 10 variables ranging from year 1947 to 2015 that includes the year, month, number of national politicians and S&P closing values. The total merged dataset with all three dataframes has 822 observations and 11 variables from years 1947 to 2015 with the year, month, number of national politicians, closing S&P values, and unemployment percentage.

```




